name: off_the_shelf
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^12.0.4
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  fpdart: ^0.3.0
  get_storage: ^2.0.3
  google_sign_in: ^5.4.2
  http: ^0.13.5
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  routemaster: ^1.0.1
  timezone: ^0.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
