// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0ZQqO1SjVaR0hleEaIK_YfQayks1gyg',
    appId: '1:349450474975:android:04393fb8c46e820013206a',
    messagingSenderId: '349450474975',
    projectId: 'off-the-shelf-d5433',
    storageBucket: 'off-the-shelf-d5433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFpMn47-EGRxpqhRq9gjE7CiyvxGApTY',
    appId: '1:349450474975:ios:11955f3f53fd1ebd13206a',
    messagingSenderId: '349450474975',
    projectId: 'off-the-shelf-d5433',
    storageBucket: 'off-the-shelf-d5433.appspot.com',
    androidClientId: '349450474975-9doijpe4qf2i5oa85mlhf7sus4boo3c4.apps.googleusercontent.com',
    iosClientId: '349450474975-hb6f9k472ts95fghqrtmp2rhu9scg7d0.apps.googleusercontent.com',
    iosBundleId: 'com.devritik.offTheShelf',
  );
}
